### PR TITLE
This fixes issue 1

### PR DESCRIPTION
**Pull request by JoelGodOfwar**
These 4 lines of code fix issue #1, by grabbing the isSilent, and CustomName from the dragon before it is removed, and then set them on the newly spawned dragon.
Which because the entity IDs are different, one can not do using ChunkLoadEvent, and CreatureSpawnEvent, because CreatureSpawnEvent is called before ChunkLoadEvent,

### CODE REVIEW

**Comment by EricLangezaal** [comment]
As I explained before, this is not something I have to add to my plugin. I don't have the time to update my plugin with new features and won't push out an update that only changes something relevant to you. This is also not the proper way to fix this, that would be copying the entire entity over (not just the properties **you** are interested in). As said before I don't have time to fix that now.

"Which because the entity IDs are different, one can not do using ChunkLoadEvent, and CreatureSpawnEvent, because CreatureSpawnEvent is called before ChunkLoadEvent," Not true at all. The code in my ChunkLoadEvent spawns a new dragon. This triggers a CreatureSpawnEvent in the next tick. Yes their ID's are different. That's why I suggested you identify them based on their location.

**Comment by JoelGodOfwar** [comment]
I did not intend to insult you in any way.

**Comment by EricLangezaal** [comment]
You didn't. Looking back at my comment my tone was a bit harsh which wasn't intended. The content of the message still holds though :).

**Comment by JoelGodOfwar** [comment]
I found a solution, for some reason it didn't dawn on me to use the ChunkUnloadEvent to copy the dragons into an ArrayList, and then when CreatureSpawnEvent fires iterate through the ArrayList checking the X, Y, Z locations, and re-silence them.
My only question is, will this create a slow memory leak, because until the plugin is restarted, the ArrayList is not cleared?

	ArrayList<Entity> dragons = new ArrayList<Entity>();
	@EventHandler
	public void onChunkUnload(ChunkUnloadEvent event){
		Entity[] entities = event.getChunk().getEntities();
		for (int i = 0; i < entities.length; i++) {
			if(entities[i] instanceof EnderDragon){
				if(entities[i].isSilent()){
					dragons.add(entities[i]);
				}
			}
		}
	}
	@EventHandler
	public void onCreatureSpawn(CreatureSpawnEvent event){
		LivingEntity entity = event.getEntity();
		SpawnReason reason = event.getSpawnReason();
		if(reason.equals(SpawnReason.INFECTION)||reason.equals(SpawnReason.CURED)){
			String name = entity.getCustomName();
			if(name != null){
				if(name.equalsIgnoreCase("silenced")){
					entity.setSilent(true);
					if(debug){logDebug("" + entity.getType().toString() + " has been ReSilenced");};
				}
			}
		}
		if(entity instanceof EnderDragon && reason.equals(SpawnReason.CUSTOM)){
			Location loc = entity.getLocation();
			int X = loc.getBlockX();
			int Y = loc.getBlockY();
			int Z = loc.getBlockZ();
			for(Entity dragon : dragons){
				Location loc2 = dragon.getLocation();
				int X2 = loc2.getBlockX();
				int Y2 = loc2.getBlockY();
				int Z2 = loc2.getBlockZ();
				if(X == X2 && Y == Y2 && Z == Z2){
					entity.setSilent(dragon.isSilent());
					if(debug){logDebug("" + entity.getType().toString() + " has been ReSilenced");};
				}
			}
		}
	}

**Comment by EricLangezaal** [comment]
Good, that's indeed what I meant you could do/try in my original post. The memory leak is not very likely, but I would improve this to get better performance. I am not going to fully code it for you, but a couple of hints:
- Once you reSilence a dragon, you no longer need to have it in your list. Now how do you modify a list from within a loop going over it? Take a look at [Iterators](https://www.w3schools.com/java/java_iterator.asp) and how you can remove elements from this list while looping over it to prevent a ConcurrentModificationException. 
- Actually the loop in CreatureSpawnEvent is not necessary with better design. Instead of saving the whole entity in your list (which is also not optimal as that is a lot of info), just save its **location** in ChunkLoadEvent if it should be silenced. Then in CreatureSpawnEvent you can check if dragons.contains(entity.getLocation()) which is optimised more. If so you know to make it silent again and can remove it from your list. This will work as the newly spawned dragon will have the exact coordinates of the old one and the changes of two dragons having the same coords are practically 0 (it has double floating point precision).
- You can also make the loop inside ChunkLoadEvent a little prettier. You don't require the index, so just loop over the Entities `for (Entity entity: event.getChunk().getEntities())`. Even this can be improved, as Spigot allows you to filter for one entity type directly, using this [method](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#getEntitiesByClass(java.lang.Class)).

**Pull request closed without merging**
